### ISSUE TITLE
Automat 24.8.0 breaks with Twisted 23.8.0

### ISSUE THREAD

**Issue by RazvanLiviuVarzaru** [glyph/automat#159]
Hello!

It's a bit unclear for me if this should be addressed here or to Twisted.
It seems that the yesterday release of **automat** won't work anymore with Twisted 23.8.0

Environment:
    python version: 3.7.3
    twisted version: 23.8.0
    buildbot-worker version: 4.0.2
    automat version: 24.8.0

**Will lead to:**
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.7/dist-packages/twisted/scripts/twistd.py", line 29, in runApp
    runner.run()
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 370, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 437, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 446, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "/usr/local/lib/python3.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "buildbot.tac", line 9, in <module>
    from buildbot_worker.bot import Worker
  File "/usr/local/lib/python3.7/dist-packages/buildbot_worker/bot.py", line 20, in <module>
    from buildbot_worker.pb import Worker
  File "/usr/local/lib/python3.7/dist-packages/buildbot_worker/pb.py", line 23, in <module>
    from twisted.application.internet import ClientService
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/internet.py", line 44, in <module>
    from automat import MethodicalMachine  # type: ignore[import]
  File "/usr/local/lib/python3.7/dist-packages/automat/__init__.py", line 5, in <module>
    from ._typed import TypeMachineBuilder, pep614, AlreadyBuiltError, TypeMachine
builtins.SyntaxError: invalid syntax (_typed.py, line 511)
`

Rollback to 22.10 solves the issue.

**Comment by altendky** [comment]
https://github.com/glyph/automat/pull/158 would avoid your Python 3.7 install from trying to use this version of automat that is 3.8+.

**Comment by glyph** [comment]
This should be addressed now. Let me know if it's still breaking.
