### ISSUE TITLE
Tests fail if gaphviz is installed but not Twisted

### ISSUE THREAD

**Issue by toabctl** [glyph/automat#71]
Having this combination is useful because Automat and Twisted have a cicle dependency (Automat needs Twisted and Twisted needs Automat).
So not having Twisted installed leads to:

```
[    5s] test_saveOnlyImage (automat._test.test_visualize.VisualizeToolTests) ... skipped 'Twisted is not installed.'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: _visualize (unittest.loader._FailedTest)
[    5s] ----------------------------------------------------------------------
[    5s] ImportError: Failed to import test module: _visualize
[    5s] Traceback (most recent call last):
[    5s]   File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
[    5s]     module = __import__(module_name)
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_noAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_quotesAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_sortsAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_validGraphviz (automat._test.test_visualize.IntegrationTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 230, in test_validGraphviz
[    5s]     out, err = p.communicate("".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_containsMachineFeatures (automat._test.test_visualize.SpotChecks)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 247, in test_containsMachineFeatures
[    5s]     gvout = "".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: _discover (unittest.loader._FailedTest)
[    5s] ----------------------------------------------------------------------
[    5s] ImportError: Failed to import test module: _discover
[    5s] Traceback (most recent call last):
[    5s]   File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
[    5s]     module = __import__(module_name)
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_noAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_quotesAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_sortsAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_validGraphviz (automat._test.test_visualize.IntegrationTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 230, in test_validGraphviz
[    5s]     out, err = p.communicate("".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_containsMachineFeatures (automat._test.test_visualize.SpotChecks)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 247, in test_containsMachineFeatures
[    5s]     gvout = "".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_noAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_quotesAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_sortsAttrs (automat._test.test_visualize.ElementMakerTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 71, in setUp
[    5s]     from .._visualize import elementMaker
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_validGraphviz (automat._test.test_visualize.IntegrationTests)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 230, in test_validGraphviz
[    5s]     out, err = p.communicate("".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ======================================================================
[    5s] ERROR: test_containsMachineFeatures (automat._test.test_visualize.SpotChecks)
[    5s] ----------------------------------------------------------------------
[    5s] Traceback (most recent call last):
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_test/test_visualize.py", line 247, in test_containsMachineFeatures
[    5s]     gvout = "".join(sampleMachine().asDigraph())
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_methodical.py", line 356, in asDigraph
[    5s]     from ._visualize import makeDigraph
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_visualize.py", line 7, in <module>
[    5s]     from ._discover import findMachines
[    5s]   File "/home/abuild/rpmbuild/BUILD/Automat-0.6.0/automat/_discover.py", line 4, in <module>
[    5s]     from twisted.python.modules import PythonModule, getModule
[    5s] ModuleNotFoundError: No module named 'twisted'
[    5s] 
[    5s] ----------------------------------------------------------------------
```

**Comment by glyph** [comment]
Not sure exactly when this was fixed, but it's been fixed for a while:

```
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ python -c 'import automat; print(automat.__file__)'
 ↩ Mon Aug 19 10:44:08 PDT 2024
/Users/glyph/.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/__init__.py
 ↪ Mon Aug 19 10:44:08 PDT 2024 (★ python -c 'import automat; print(automat.__file__)')                            
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ python -c 'import twisted'
 ↩ Mon Aug 19 10:44:23 PDT 2024
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'twisted'
 ↪ Mon Aug 19 10:44:24 PDT 2024 (★ python -c 'import twisted') (1 seconds elapsed)                                 
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🛑 1  🐳 🫛  ⮐
  ★ python -c 'import graphviz'
 ↩ Mon Aug 19 10:44:26 PDT 2024
 ↪ Mon Aug 19 10:44:27 PDT 2024 (★ python -c 'import graphviz') (1 seconds elapsed)                                
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ pytest /Users/glyph/.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat
 ↩ Mon Aug 19 10:44:29 PDT 2024
=============================================== test session starts ===============================================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /Users/glyph
collected 82 items                                                                                                

.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_core.py ......              [  7%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_discover.py sssssssssssssss [ 25%]
sssssssss                                                                                                   [ 36%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_methodical.py ............. [ 52%]
......                                                                                                      [ 59%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_trace.py ..                 [ 62%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_type_based.py ......s...... [ 78%]
...                                                                                                         [ 81%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_visualize.py ssssssssssssss [ 98%]
s                                                                                                           [100%]

========================================= 42 passed, 40 skipped in 0.10s ==========================================
 ↪ Mon Aug 19 10:44:29 PDT 2024 (★ pytest /Users/glyph/.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat)
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ 
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ python -c 'import twisted'
 ↩ Mon Aug 19 10:44:23 PDT 2024
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'twisted'
 ↪ Mon Aug 19 10:44:24 PDT 2024 (★ python -c 'import twisted') (1 seconds elapsed)                                 
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🛑 1  🐳 🫛  ⮐
  ★ python -c 'import graphviz'
 ↩ Mon Aug 19 10:44:26 PDT 2024
 ↪ Mon Aug 19 10:44:27 PDT 2024 (★ python -c 'import graphviz') (1 seconds elapsed)                                
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ pytest /Users/glyph/.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat
 ↩ Mon Aug 19 10:44:29 PDT 2024
=============================================== test session starts ===============================================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /Users/glyph
collected 82 items                                                                                                

.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_core.py ......              [  7%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_discover.py sssssssssssssss [ 25%]
sssssssss                                                                                                   [ 36%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_methodical.py ............. [ 52%]
......                                                                                                      [ 59%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_trace.py ..                 [ 62%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_type_based.py ......s...... [ 78%]
...                                                                                                         [ 81%]
.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat/_test/test_visualize.py ssssssssssssss [ 98%]
s                                                                                                           [100%]

========================================= 42 passed, 40 skipped in 0.10s ==========================================
 ↪ Mon Aug 19 10:44:29 PDT 2024 (★ pytest /Users/glyph/.virtualenvs/tmp-e0e4494747e615/lib/python3.12/site-packages/automat)
glyph@arabella:~  🏰 tmp-e0e4494747e615  🐚 🔑   🎗  📌⏰  🐳 🫛  ⮐
  ★ 

```
